### PR TITLE
Connection class hierarchy

### PR DESCRIPTION
**Pull request by jlrobins**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Unit tests are present
- [x] Have you validated this change locally?

## Summary of Changes

- Make a class hierarchy for all data connection Connection types:
    - Root is protocol `noteable.sql.connection.Connection`
    - Then minimal base class with an iota of constructor responsibility, `noteable.sql.connection.BaseConnection`
    - Then concrete + interemediate base class for all SQLAlchemy-based types, `noteable.sql.sqlalchemy.SQLAlchemyConnection`
    - Then for the SQLAlchemy-based types that need to do some extra bits, namely what used to be post-processing, concrete subclasses.
    
class_hierarchy

Concrete classes are registered according to the driver name they should respond to via registration decorator `noteable.sql.connection.connection_class`. Classes may be multiply-registered, as is the case for SQLAlchemyConnection and PostgreSQLConnection.

There's a second hierarchy for representing results from queries. Base protocol is `noteable.sql.connection.ResultSet`. Only current implementation is `noteable.sql.sqlalchemy.SQLAlchemyResult`, which all of the `SQLAlchemyConnection` inheritor implementations will return.

Bootstrapping datasources now looks up the class to use given the drivername found in the metadata dict from vault injection, then defers to the registered class to handle all of the rest of the particulars.

The sql magics (and therefore also the meta-commands) now operate in terms of methods on protocol `Connection`, most specifically `execute`, taking a text query and returning a `ResultSet`. Currently in the codebase there are no non-SQLAlchemy-based implementations, but there are already initial guards in place preventing schema introspection from happening against a non-SQLAlchemy-based Connection. I do plan on supporting introspection on some of those, but that's future work. Supporting so will need more methods defined on Connection, with SQLAlchemyConnection growing most of the code that's currently in the meta_commands package. That will be the next implementation step, and will most likely allow me to cleanly fix schema introspection issue vs Snowflake (@noteabledave ).

This clears the way to have a notebook _define_ a new Connection implementation class, `@connection_class()` register it, then run a SQL cell of that datasource driver type and the just-in-time bootstrapping will use the new class definition.

This will also clear the way for a family of Connection subclasses which _do not_ descend from `SQLAlchemyConnection`, namely for those which interact with non-SQL / non-SQLAlchemyable sources of data, but still return rows/columns expressible in a new `ResultSet` implementation.

This is step KM3) in [the project plan](https://docs.google.com/document/d/1mYZp5O4IlqFi1IexLdCtr8ihnEq6KWzbDJGzpnHnjDo/edit).

### CODE REVIEW

**Comment by jlrobins** [comment]
From skaffold dev, note class name for the PG connection.

Screenshot 2023-06-22 at 5 22 33 PM

**Comment by jlrobins** [comment]
And with a **defined-in-notebook class** for Jira extending from BaseConnection registered to handle CockroachDB connection types, can then grab hostname, user, and API token from password fields of a CockroachDB connection to then query Jira issues!

Screenshot 2023-06-22 at 6 01 16 PM

**Comment by jlrobins** [comment]
The class definition:

```
@connection_class('cockroachdb')
class JiraConnection(BaseConnection):
    
    is_sqlalchemy_based = False
    
    def __init__(
        self,
        cell_handle: str,
        metadata: Dict[str, Any],
        dsn_dict: Dict[str, Any],
        create_engine_kwargs: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(cell_handle, metadata['name'])
        
        # Steal user, password, host, assemble a jira client
        user = dsn_dict['username']
        token = dsn_dict['password']
        url = f"https://{dsn_dict['host']}/"
        
        self.jira_client = jira.JIRA(url, basic_auth=(user, token))
        
    def execute(self, statement: str, bind_dict: Dict[str, Any]) -> ResultSet:
        query, projection_list = self._extract_projection(statement)
        query, maxResults = self._parse_out_limit(query)
                        
        issues = self.jira_client.search_issues(query, maxResults=maxResults)
        
        return JiraResult(issues, projection_list)
        
    def close(self):
        pass
    
    def _parse_out_limit(self, s):
        match = re.search(r'(.*)(LIMIT[ \t\n]+(\d+))', s, re.IGNORECASE + re.DOTALL)
        if match:
            return match.group(1).strip(), int(match.group(3))
        else:
            return s, 50
        
    def _extract_projection(self, s) -> Tuple[str,List[str]]:
        match = re.search(r'(SELECT[ \t\n]+(.*?)[ \t\n]+WHERE)(.*)', s, re.IGNORECASE + re.DOTALL)
        projections = ['id'] # minimal default.
        if match:
            projections = [item.strip() for item in match.group(2).split(',')]
            rest = match.group(3).strip()
        else:
            rest = s
            
        return rest, projections
        
        
class JiraResult(ResultSet):
    """
    Results of a query from Jira.
    """

    keys: Optional[List[str]] = None
    rows: Optional[list] = None
    rowcount: Optional[int] = None
    has_results_to_report: bool = True

    def __init__(self, jql_results, projection_list: List[str]):
        rows = []
        for issue in jql_results:
            row = []
            for fieldname in projection_list:
                row.append(self._extract_from_jira_item(fieldname, issue))
            rows.append(row)
        
        self.rows = rows
        self.keys = projection_list
        
        
    def _extract_from_jira_item(self, name, issue):
        if name in ('id', 'key'):
            return issue.key
        
        elif name in ('url', 'permalink'):
            return issue.permalink()
        
        else:
            return getattr(issue.fields, name)
```

**Comment by jlrobins** [comment]
... and it denies running meta-commands (introspection stuff) at this time:

Screenshot 2023-06-22 at 6 05 29 PM

**Comment by jlrobins** [comment]
And an example of one-two punch of doing Jira query for raw data, then DuckDB over the dataframe to produce aggregate processing that JQL can't do:
Screenshot 2023-06-22 at 6 38 35 PM

**Comment by jlrobins** [comment]
And with some additional smarts within `JiraConnection.execute()`, can handle JinjaSQL'd parameters. This was kinda PITA, and can be made easier in the near future:
Screenshot 2023-06-22 at 7 06 07 PM

**Review by tizz98 — APPROVED** [review]
very pleasant to read

**Pull request merged**
